version: '3.4'

services:

  database:
    image: redis:alpine
    hostname: redis
    container_name: redis-alpine
    ports:
      - 6379:6379
    environment:
      - REDIS_REPLICATION_MODE=master
    command: "redis-server"
    
  main:
    build:
      dockerfile: ./app/Dockerfile
      context: .
    network_mode: host
    command: python3 main.py
